### ISSUE TITLE
BoP integration is broken

### ISSUE THREAD

**Issue by TheDogOfChaos** [Gregified-Modded/Gregified-Integrations#2]
### Relevant mod:

Biomes O Plenty

### Bug Description:

The game crashes on worldload with the following error and stacktrace:
```
[18:37:28] [Render thread/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: DEAD_BOAT
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: com.gregtechceu.gtceu.client.ClientProxy@595f0354 registerPackFinders(Lnet/minecraftforge/event/AddPackFindersEvent;)V
java.lang.NoSuchFieldError: DEAD_BOAT
	at TRANSFORMER/gregifiedintegrations@1.3.10/com.therealm18studios.gregifiedintegrations.data.recipe.configurable.addition.BiomesOPlentyRecipeAddition.harderBiomesOPlentyRecipes(BiomesOPlentyRecipeAddition.java:33)
	at TRANSFORMER/gregifiedintegrations@1.3.10/com.therealm18studios.gregifiedintegrations.data.recipe.configurable.addition.BiomesOPlentyRecipeAddition.init(BiomesOPlentyRecipeAddition.java:25)
	at TRANSFORMER/gregifiedintegrations@1.3.10/com.therealm18studios.gregifiedintegrations.GIGTAddon.addRecipes(GIGTAddon.java:40)
	at TRANSFORMER/gtceu@1.4.4/com.gregtechceu.gtceu.common.data.GTRecipes.lambda$recipeAddition$1(GTRecipes.java:90)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at TRANSFORMER/gtceu@1.4.4/com.gregtechceu.gtceu.common.data.GTRecipes.recipeAddition(GTRecipes.java:90)
	at TRANSFORMER/gtceu@1.4.4/com.gregtechceu.gtceu.common.CommonProxy.registerPackFinders(CommonProxy.java:268)
	at TRANSFORMER/gtceu@1.4.4/com.gregtechceu.gtceu.common.__CommonProxy_registerPackFinders_AddPackFindersEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at LAYER PLUGIN/javafmllanguage@1.20.1-47.3.7/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114)
	at LAYER PLUGIN/fmlcore@1.20.1-47.3.7/net.minecraftforge.fml.ModLoader.lambda$postEvent$29(ModLoader.java:326)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at LAYER PLUGIN/fmlcore@1.20.1-47.3.7/net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:227)
	at LAYER PLUGIN/fmlcore@1.20.1-47.3.7/net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:326)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.packs.repository.ServerPacksSource.m_245786_(ServerPacksSource.java:52)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.packs.repository.ServerPacksSource.m_247728_(ServerPacksSource.java:57)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.doLoadLevel(WorldOpenFlows.java:176)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233145_(WorldOpenFlows.java:169)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.handler$fpe000$onLoadLevel(WorldOpenFlows.java:2032)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233133_(WorldOpenFlows.java)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101744_(WorldSelectionList.java:575)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101704_(WorldSelectionList.java:474)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_6375_(WorldSelectionList.java:413)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.components.AbstractSelectionList.m_6375_(AbstractSelectionList.java:298)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:38)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:92)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:89)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:189)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:188)
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
	at TRANSFORMER/fpsreducer@1.20-2.5/bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133)
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at MC-BOOTSTRAP/org.lwjgl@3.3.1+7/org.lwjgl.system.JNI.invokeV(Native Method)
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.systems.RenderSystem.handler$fjn000$handleWaitEventsTimeout(RenderSystem.java:2008)
	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1173)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.7/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.7/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.7/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

[18:37:28] [Render thread/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Caught exception during event net.minecraftforge.event.AddPackFindersEvent@70181207 dispatch for modid gtceu
java.lang.NoSuchFieldError: DEAD_BOAT
	at com.therealm18studios.gregifiedintegrations.data.recipe.configurable.addition.BiomesOPlentyRecipeAddition.harderBiomesOPlentyRecipes(BiomesOPlentyRecipeAddition.java:33) ~[gregifiedintegrations-1.20.1-1.3.10.jar%23705!/:?] {re:classloading}
	at com.therealm18studios.gregifiedintegrations.data.recipe.configurable.addition.BiomesOPlentyRecipeAddition.init(BiomesOPlentyRecipeAddition.java:25) ~[gregifiedintegrations-1.20.1-1.3.10.jar%23705!/:?] {re:classloading}
	at com.therealm18studios.gregifiedintegrations.GIGTAddon.addRecipes(GIGTAddon.java:40) ~[gregifiedintegrations-1.20.1-1.3.10.jar%23705!/:?] {re:classloading}
	at com.gregtechceu.gtceu.common.data.GTRecipes.lambda$recipeAddition$1(GTRecipes.java:90) ~[gtceu-1.20.1-1.4.4.jar%23706!/:1.4.4] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at com.gregtechceu.gtceu.common.data.GTRecipes.recipeAddition(GTRecipes.java:90) ~[gtceu-1.20.1-1.4.4.jar%23706!/:1.4.4] {re:classloading}
	at com.gregtechceu.gtceu.common.CommonProxy.registerPackFinders(CommonProxy.java:268) ~[gtceu-1.20.1-1.4.4.jar%23706!/:1.4.4] {re:classloading}
	at com.gregtechceu.gtceu.common.__CommonProxy_registerPackFinders_AddPackFindersEvent.invoke(.dynamic) ~[gtceu-1.20.1-1.4.4.jar%23706!/:1.4.4] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.20.1-47.3.7.jar%23928!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$29(ModLoader.java:326) ~[fmlcore-1.20.1-47.3.7.jar%23927!/:?] {re:mixin}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:227) ~[fmlcore-1.20.1-47.3.7.jar%23927!/:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:326) ~[fmlcore-1.20.1-47.3.7.jar%23927!/:?] {re:mixin}
	at net.minecraft.server.packs.repository.ServerPacksSource.m_245786_(ServerPacksSource.java:52) ~[client-1.20.1-20230612.114412-srg.jar%23926!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.packs.repository.ServerPacksSource.m_247728_(ServerPacksSource.java:57) ~[client-1.20.1-20230612.114412-srg.jar%23926!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.doLoadLevel(WorldOpenFlows.java:176) ~[client-1.20.1-20230612.114412-srg.jar%23926!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233145_(WorldOpenFlows.java:169) ~[client-1.20.1-20230612.114412-srg.jar%23926!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.handler$fpe000$onLoadLevel(WorldOpenFlows.java:2032) ~[client-1.20.1-20230612.114412-srg.jar%23926!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233133_(WorldOpenFlows.java) ~[client-1.20.1-20230612.114412-srg.jar%23926!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101744_(WorldSelectionList.java:575) ~[client-1.20.1-20230612.114412-srg.jar%23926!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_screen_skipped.WorldSelectionListMixin,pl:mixin:APP:fancymenu.mixins.json:client.MixinWorldListEntry,pl:mixin:APP:aether.mixins.json:client.WorldListEntryMixin,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinWorldListEntry,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101704_(WorldSelectionList.java:474) ~[client-1.20.1-20230612.114412-srg.jar%23926!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_screen_skipped.WorldSelectionListMixin,pl:mixin:APP:fancymenu.mixins.json:client.MixinWorldListEntry,pl:mixin:APP:aether.mixins.json:client.WorldListEntryMixin,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinWorldListEntry,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_6375_(WorldSelectionList.java:413) ~[client-1.20.1-20230612.114412-srg.jar%23926!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_screen_skipped.WorldSelectionListMixin,pl:mixin:APP:fancymenu.mixins.json:client.MixinWorldListEntry,pl:mixin:APP:aether.mixins.json:client.WorldListEntryMixin,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinWorldListEntry,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.components.AbstractSelectionList.m_6375_(AbstractSelectionList.java:298) ~[client-1.20.1-20230612.114412-srg.jar%23926!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:yungsmenutweaks.mixins.json:AbstractSelectionListMixin,pl:mixin:APP:yungsmenutweaks_forge.mixins.json:AbstractSelectionListMixinForge,pl:mixin:APP:fancymenu.mixins.json:client.IMixinAbstractSelectionList,pl:mixin:APP:fancymenu.mixins.json:client.MixinAbstractSelectionList,pl:mixin:APP:refurbished_furniture.common.mixins.json:client.AbstractSelectionListMixin,pl:mixin:APP:kubejs-common.mixins.json:AbstractSelectionListMixin,pl:mixin:APP:configured.common.mixins.json:client.AbstractSelectionListMixin,pl:mixin:APP:yacl.mixins.json:AbstractSelectionListMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:38) ~[client-1.20.1-20230612.114412-srg.jar%23926!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:92) ~[client-1.20.1-20230612.114412-srg.jar%23926!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ldlib-common.mixins.json:accessor.MouseHandlerAccessor,pl:mixin:APP:supplementaries-common.mixins.json:MouseHandlerMixin,pl:mixin:APP:corgilib-common.mixins.json:client.MixinMouseHandler,pl:mixin:APP:emi.mixins.json:MouseMixin,pl:mixin:APP:konkrete.mixin.json:MixinMouseHandler,pl:mixin:APP:creativecore.mixins.json:MouseHandlerAccessor,pl:mixin:APP:fancymenu.mixins.json:client.MixinMouseHandler,pl:mixin:APP:zume.mixins.json:lexforge.MouseHandlerMixin,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:mixins.cofhcore.json:MouseHandlerMixin,pl:mixin:APP:figura-common.mixins.json:input.MouseHandlerMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMouseHandler,pl:mixin:APP:jeg.mixins.json:client.MouseHandlerMixin,pl:mixin:APP:create.mixins.json:accessor.MouseHandlerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437) ~[client-1.20.1-20230612.114412-srg.jar%23926!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:yungsmenutweaks.mixins.json:ScreenMixin,pl:mixin:APP:cumulus_menus.mixins.json:client.accessor.ScreenAccessor,pl:mixin:APP:emi.mixins.json:ScreenMixin,pl:mixin:APP:konkrete.mixin.json:IMixinScreen,pl:mixin:APP:fancymenu.mixins.json:client.IMixinScreen,pl:mixin:APP:fancymenu.mixins.json:client.MixinScreen,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:APP:figura-common.mixins.json:gui.ScreenAccessor,pl:mixin:APP:figura-common.mixins.json:gui.ScreenMixin,pl:mixin:APP:cold_sweat.mixin.json:MixinChatClicked,pl:mixin:APP:aether.mixins.json:client.accessor.ScreenAccessor,pl:mixin:APP:controlling.mixins.json:AccessScreen,pl:mixin:APP:nerb-common.mixins.json:ScreenMixin,pl:mixin:APP:refurbished_furniture.common.mixins.json:client.ScreenAccessor,pl:mixin:APP:kubejs-common.mixins.json:ScreenMixin,pl:mixin:APP:configured.common.mixins.json:client.ScreenMixin,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen,pl:mixin:APP:mixins.epp.json:MixinScreen,pl:mixin:APP:ae2.mixins.json:WrappedGenericStackTooltipModIdMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23926!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ldlib-common.mixins.json:accessor.MouseHandlerAccessor,pl:mixin:APP:supplementaries-common.mixins.json:MouseHandlerMixin,pl:mixin:APP:corgilib-common.mixins.json:client.MixinMouseHandler,pl:mixin:APP:emi.mixins.json:MouseMixin,pl:mixin:APP:konkrete.mixin.json:MixinMouseHandler,pl:mixin:APP:creativecore.mixins.json:MouseHandlerAccessor,pl:mixin:APP:fancymenu.mixins.json:client.MixinMouseHandler,pl:mixin:APP:zume.mixins.json:lexforge.MouseHandlerMixin,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:mixins.cofhcore.json:MouseHandlerMixin,pl:mixin:APP:figura-common.mixins.json:input.MouseHandlerMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMouseHandler,pl:mixin:APP:jeg.mixins.json:client.MouseHandlerMixin,pl:mixin:APP:create.mixins.json:accessor.MouseHandlerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:189) ~[client-1.20.1-20230612.114412-srg.jar%23926!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ldlib-common.mixins.json:accessor.MouseHandlerAccessor,pl:mixin:APP:supplementaries-common.mixins.json:MouseHandlerMixin,pl:mixin:APP:corgilib-common.mixins.json:client.MixinMouseHandler,pl:mixin:APP:emi.mixins.json:MouseMixin,pl:mixin:APP:konkrete.mixin.json:MixinMouseHandler,pl:mixin:APP:creativecore.mixins.json:MouseHandlerAccessor,pl:mixin:APP:fancymenu.mixins.json:client.MixinMouseHandler,pl:mixin:APP:zume.mixins.json:lexforge.MouseHandlerMixin,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:mixins.cofhcore.json:MouseHandlerMixin,pl:mixin:APP:figura-common.mixins.json:input.MouseHandlerMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMouseHandler,pl:mixin:APP:jeg.mixins.json:client.MouseHandlerMixin,pl:mixin:APP:create.mixins.json:accessor.MouseHandlerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23926!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin,pl:mixin:A}
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:188) ~[client-1.20.1-20230612.114412-srg.jar%23926!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ldlib-common.mixins.json:accessor.MouseHandlerAccessor,pl:mixin:APP:supplementaries-common.mixins.json:MouseHandlerMixin,pl:mixin:APP:corgilib-common.mixins.json:client.MixinMouseHandler,pl:mixin:APP:emi.mixins.json:MouseMixin,pl:mixin:APP:konkrete.mixin.json:MixinMouseHandler,pl:mixin:APP:creativecore.mixins.json:MouseHandlerAccessor,pl:mixin:APP:fancymenu.mixins.json:client.MixinMouseHandler,pl:mixin:APP:zume.mixins.json:lexforge.MouseHandlerMixin,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:mixins.cofhcore.json:MouseHandlerMixin,pl:mixin:APP:figura-common.mixins.json:input.MouseHandlerMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMouseHandler,pl:mixin:APP:jeg.mixins.json:client.MouseHandlerMixin,pl:mixin:APP:create.mixins.json:accessor.MouseHandlerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.3.1.jar%2386!/:build 7] {}
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133) ~[FpsReducer2-forge-1.20-2.5.jar%23681!/:1.20-2.5] {re:classloading}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%2386!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%2398!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar%2386!/:build 7] {re:mixin}
	at com.mojang.blaze3d.systems.RenderSystem.handler$fjn000$handleWaitEventsTimeout(RenderSystem.java:2008) ~[client-1.20.1-20230612.114412-srg.jar%23926!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:RenderTexturesMixin,pl:mixin:APP:fpsreducer.mixins.json:RenderSystemMixin,pl:mixin:APP:embeddium.mixins.json:workarounds.event_loop.RenderSystemMixin,pl:mixin:A}
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java) ~[client-1.20.1-20230612.114412-srg.jar%23926!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:RenderTexturesMixin,pl:mixin:APP:fpsreducer.mixins.json:RenderSystemMixin,pl:mixin:APP:embeddium.mixins.json:workarounds.event_loop.RenderSystemMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1173) ~[client-1.20.1-20230612.114412-srg.jar%23926!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23926!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin,pl:mixin:APP:notenoughcrashes.forge.mixins.json:client.MixinMain,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.7.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.7.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.7.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[?:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[?:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?] {}
```

**Comment by CristalGaming** [comment]
i found out that is due the 19.0.0.1 version of biomes o' plenty. try using 18.0.0.598

**Comment by TheRealM18** [comment]
fixed in latest
